name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          build-essential git valgrind cppcheck \
          libasound2-dev libx11-dev libxrandr-dev libxi-dev \
          libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev \
          libwayland-dev libxkbcommon-dev
    - name: Build project
      run: |
        make build

    - name: Run tests (Makefile targets)
      run: |
        make test
