name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential valgrind cppcheck
    - name: Setup Raylib (if missing)
      run: |
        make setup-raylib

    - name: Build project
      run: |
        make -j$(nproc)

    - name: Run cppcheck (Makefile target)
      run: |
        make cppcheck || true

    - name: Run tests (Makefile targets)
      run: |
        make test
        make valgrind-test || echo "valgrind-test failed or valgrind missing"
